---
- name: install nginx
  yum: name=nginx

- name: configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nginx

- include: configure-ssl.yml

- name: configure vhosts
  include: vhost.yml
  args:
    vhost_name: "{{ item.name }}"
    vhost_default: "{{ item.default|default(true) }}"
    vhost_pool: "{{ item.pool }}"
    vhost_params: "{{ item.params|default({}) }}"
  with_items: "{{ nginx_vhosts }}"

- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes
